### ISSUE TITLE
Several packages fail with error "no tty present and no askpass program specified"

### ISSUE THREAD

**Issue by rolfw** [boxen/puppet-brewcask#19] opened 2014-08-22 07:00 UTC
This error output is for ```package { 'totalspaces': provider => 'brewcask', install_options => ['--appdir=/Applications'] }```, but for my specific manifest the following casks also fail with the same error (all with same Puppet syntax):
* totalfinder
* timecamp
* kaleidoscope
* graphviz
* airdisplay
* lastpass-universal
* silverlight
* paragon-ntfs

Many other packages install without problems. I've repeated the process countless times and it keeps failing with the same packages.

I found two issues for other projects that might be discussing the same underlying problem:

* [This issue at caskroom/homebrew-cask](https://github.com/phinze/puppet-brewcask/issues/new) suggests a workaround to execute ```brew install cask``` as sudo. Boxen won't allow this though.
* From what I understand from [this related issue at kitchenplan/chef-homebrewalt](https://github.com/kitchenplan/chef-homebrewalt/issues/8) is that the error occurs when there are multiple packages to be installed, with sudo expiring after some time causing any packages that haven't been installed at that time to fail. In my case it happens always though, even when there is only one package to be installed.

```
Error: Execution of 'brew cask install totalspaces --appdir=/Applications' returned 1: ==> Downloading http://downloads.binaryage.com/TotalSpaces2-2.2.6.zip
Already downloaded: /Library/Caches/Homebrew/totalspaces-2.2.6.zip
==> Running installer for totalspaces; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
Error: Command failed to execute!

==> Failed command:
["/usr/bin/sudo", "-E", "--", "/usr/sbin/installer", "-pkg", "#<Pathname:/opt/homebrew-cask/Caskroom/totalspaces/2.2.6/TotalSpaces2.pkg>", "-target", "/"]

==> Output of failed command:
sudo: no tty present and no askpass program specified


==> Exit status of failed command:
#<Process::Status: pid 1047 exit 1>
==> sudo: no tty present and no askpass program specified
```

**Comment by jen20** [comment] 2015-02-16 15:25
For packages where there's a large download involved (e.g. java) I've found it helpful to run `while true; do sudo echo "Keeping sudo alive..."; sleep 60; done` in a separate terminal to keep askpass timer from resetting.

**Comment by radeksimko** [comment] 2015-03-01 20:25
Closing this as a duplicate of #22 as that issue is a little bit more generic.

**Closed by radeksimko** 2015-03-01 20:25 UTC
